### ISSUE TITLE
The Pseudolink server control may contain only property declarations, and plain text was found

### ISSUE THREAD

**Issue by vorou** [seanofw/Redesigner#1]
Was really happy to finally find this tool, and it fixed a couple files in our project swiftly, but then it failed with:

```
Redesigner.exe: C:\Users\vorou\code\elba\IB\Front\Business\PlannedPayments\PlannedPaymentLightbox\PlannedPaymentLightboxControl.ascx: Failed to load markup file:
Line 191: The Pseudolink server control may contain only property declarations, and plain text was found.
```

And the line from the markup is:

```
<ib:Pseudolink ID="ScheduleLink" class="<%#IconHelpers.GetClass(Icon.AutoDocument) %>" runat="server" OnClick="onSchedule">Создавать такую же платёжку ежемесячно</ib:Pseudolink>
```

Pseudolink is our custom control. Its base class from `System.Web` namespace is `System.Web.UI.WebControls.WebControl`. 

What exactly leads to Redesigner requiring that it mustn't have plain text? Is there a quick fix for it (either in our codebase, or in Redesigner), or is it a fundamental problem?

**Comment by seanofw** [comment]
A lot depends on the code in you `PseudoLink` control itself:  Redesigner depends on the control's code being a precise, accurate description of the desired usage, while WebForms allows more "fuzzy" usages and will often stick data in "best guess" locations.

In this case, you probably have a `Text` property that that inner content is supposed to end up in, and it (and the class) are declared in such a way that WebForms will allow any inner text to be inserted into it, but such that the _proper_ use of the property in the markup is as an attribute:  `<ib:PseudoLink ... Text="Создавать такую же платёжку ежемесячно" />`

Since I don't have access to your `PseudoLink` class's source code, though, I can't say for sure how Redesigner is interpreting it.

**Comment by seanofw** [comment]
Since it's been months since I last heard from you, I'm going to close this issue.
